### ISSUE TITLE
Try to use an ORM to access your DB

### ISSUE THREAD

**Issue by anhnguyen-pizzahut** [ntnhan2266/news-feeds-service#1]
Hey, this is Duy Anh from Pizzahut Digital Venture

It's cleaner for your codes to try using an ORM to access your DB. One of my best pick would be sequelize for nodejs

**Comment by ntnhan2266** [comment]
I updated API code with using Sequelize.

**Comment by anhnguyen-pizzahut** [comment]
@ntnhan2266 Thanks for resolving this
