### ISSUE TITLE
Dangerously setting HTML content

### ISSUE THREAD

**Issue by anhnguyen-pizzahut** [ntnhan2266/news-feeds-service#2]
```
<p
              className="newsfeed-content"
              dangerouslySetInnerHTML={{
                __html: this.refactorContent(data.content)
              }}
/>
```
Using this in your code is not recommended, is there any other better way around this?

**Comment by ntnhan2266** [comment]
I found that description field is better choice for render in list. About render html with dangerouslySetInnerHTML, I use DOMPurify to sanitize HTML before inserting it in the DOM via dangerouslySetInnerHTML.
`
{/* <p
              className="newsfeed-content"
              dangerouslySetInnerHTML={{__html: DOMPurify.sanitize(data.content) }}
/> */}
`
`
            <p className="newsfeed-content">{data.description}</p>
`
