### ISSUE TITLE
Excessive div in LoadingSpinner.tsx

### ISSUE THREAD

**Issue by anhnguyen-pizzahut** [ntnhan2266/news-feeds-service#3]
```
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
```
I have seen a lot of divs, is there a reason for that?

**Comment by ntnhan2266** [comment]
I generated custom loading spinner from [loading.io](https://loading.io/) with HTML and CSS. But I found a better solution is using `CircularProgress` component of material ui.
